obstacle_range: 2
raytrace_range: 2.0
footprint: [[2,2],[-2,2],[-2,-2],[2,-2]]
#footprint: [[0.65,0.5],[-0.65,0.5],[-0.65,-0.5],[0.65,-0.5]]

inflation_radius: 0.1
cost_scaling_factor: 10.0

#observation_sources: scan
#scan: {data_type: LaserScan, expected_update_rate: 0.5,
 # observation_persistence: 0.0, marking: true, clearing: true, max_obstacle_height: 0.4, min_obstacle_height: 0.08}



