local_costmap:
  global_frame: /vl_robot/odom
  robot_base_frame: /vl_robot/base_link
  update_frequency: 2
  publish_frequency: 0.5
  static_map: false
  rolling_window: true
  max_obstacle_width: 8.0
  max_obstacle_height: 8.0
  width: 6
  height: 6
  resolution: 0.1
  transfrom_tolerance: 0.5
