obstacle_range: 2.0
raytrace_range: 2.0
footprint: [[2,2],[-2,2],[-2,-2],[2,-2]]
#footprint: [[0.65,0.5],[-0.65,0.5],[-0.65,-0.5],[0.65,-0.5]]

inflation_radius: 3
cost_scaling_factor: 10.0
#Due to we did not merge laser data and give to VL robot
# Therefore, there is no laser information, it cannot avoid dynamic obstacles

#observation_sources: scan
#scan: {data_type: LaserScan, expected_update_rate: 0.5,
 # observation_persistence: 0.0, marking: true, clearing: true, max_obstacle_height: 0.4, min_obstacle_height: 0.08}



