obstacle_range: 2
raytrace_range: 2.0
footprint: [[1.2,1.2],[-1.2,1.2],[-1.2,-1.2],[1.2,-1.2]]
inflation_radius: 2.0
cost_scaling_factor: 10.0
#footprint: [[0.65,0.5],[-0.65,0.5],[-0.65,-0.5],[0.65,-0.5]]

#Due to we did not merge laser data and give to VL robot
# Therefore, there is no laser information, it cannot avoid dynamic obstacles
map_type: costmap
observation_sources: scan
scan: {sensor_frame: laser_link , data_type: LaserScan, topic: scan, marking: true, clearing: true}



