// Generated by gencpp from file multi_amr_nectec/pos_msg.msg
// DO NOT EDIT!


#ifndef MULTI_AMR_NECTEC_MESSAGE_POS_MSG_H
#define MULTI_AMR_NECTEC_MESSAGE_POS_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace multi_amr_nectec
{
template <class ContainerAllocator>
struct pos_msg_
{
  typedef pos_msg_<ContainerAllocator> Type;

  pos_msg_()
    : points2()
    , another_field2(0)  {
    }
  pos_msg_(const ContainerAllocator& _alloc)
    : points2(_alloc)
    , another_field2(0)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _points2_type;
  _points2_type points2;

   typedef uint8_t _another_field2_type;
  _another_field2_type another_field2;





  typedef boost::shared_ptr< ::multi_amr_nectec::pos_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multi_amr_nectec::pos_msg_<ContainerAllocator> const> ConstPtr;

}; // struct pos_msg_

typedef ::multi_amr_nectec::pos_msg_<std::allocator<void> > pos_msg;

typedef boost::shared_ptr< ::multi_amr_nectec::pos_msg > pos_msgPtr;
typedef boost::shared_ptr< ::multi_amr_nectec::pos_msg const> pos_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multi_amr_nectec::pos_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multi_amr_nectec::pos_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace multi_amr_nectec

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'multi_amr_nectec': ['/home/kanin/catkin_ws_roboware/src/multi_amr_nectec/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::multi_amr_nectec::pos_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_amr_nectec::pos_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_amr_nectec::pos_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_amr_nectec::pos_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_amr_nectec::pos_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_amr_nectec::pos_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multi_amr_nectec::pos_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "584ed9eab9daa1be705ab1b1de5c8229";
  }

  static const char* value(const ::multi_amr_nectec::pos_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x584ed9eab9daa1beULL;
  static const uint64_t static_value2 = 0x705ab1b1de5c8229ULL;
};

template<class ContainerAllocator>
struct DataType< ::multi_amr_nectec::pos_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multi_amr_nectec/pos_msg";
  }

  static const char* value(const ::multi_amr_nectec::pos_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multi_amr_nectec::pos_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] points2\n\
uint8 another_field2\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::multi_amr_nectec::pos_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multi_amr_nectec::pos_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points2);
      stream.next(m.another_field2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pos_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multi_amr_nectec::pos_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multi_amr_nectec::pos_msg_<ContainerAllocator>& v)
  {
    s << indent << "points2[]" << std::endl;
    for (size_t i = 0; i < v.points2.size(); ++i)
    {
      s << indent << "  points2[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points2[i]);
    }
    s << indent << "another_field2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.another_field2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTI_AMR_NECTEC_MESSAGE_POS_MSG_H
