// Generated by gencpp from file beginner_tutorials/cmd_vel.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_CMD_VEL_H
#define BEGINNER_TUTORIALS_MESSAGE_CMD_VEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>

namespace beginner_tutorials
{
template <class ContainerAllocator>
struct cmd_vel_
{
  typedef cmd_vel_<ContainerAllocator> Type;

  cmd_vel_()
    : robot_cmd_vel()  {
    }
  cmd_vel_(const ContainerAllocator& _alloc)
    : robot_cmd_vel(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Twist_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Twist_<ContainerAllocator> >::other >  _robot_cmd_vel_type;
  _robot_cmd_vel_type robot_cmd_vel;





  typedef boost::shared_ptr< ::beginner_tutorials::cmd_vel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::cmd_vel_<ContainerAllocator> const> ConstPtr;

}; // struct cmd_vel_

typedef ::beginner_tutorials::cmd_vel_<std::allocator<void> > cmd_vel;

typedef boost::shared_ptr< ::beginner_tutorials::cmd_vel > cmd_velPtr;
typedef boost::shared_ptr< ::beginner_tutorials::cmd_vel const> cmd_velConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::cmd_vel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::cmd_vel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/kanin/catkin_ws_roboware/src/beginner_tutorials/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::cmd_vel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::cmd_vel_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::cmd_vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::cmd_vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::cmd_vel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::cmd_vel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::cmd_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "156dca494411a2fd8068c53948502b64";
  }

  static const char* value(const ::beginner_tutorials::cmd_vel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x156dca494411a2fdULL;
  static const uint64_t static_value2 = 0x8068c53948502b64ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::cmd_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/cmd_vel";
  }

  static const char* value(const ::beginner_tutorials::cmd_vel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::cmd_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Twist[] robot_cmd_vel\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::beginner_tutorials::cmd_vel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::cmd_vel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_cmd_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cmd_vel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::cmd_vel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::cmd_vel_<ContainerAllocator>& v)
  {
    s << indent << "robot_cmd_vel[]" << std::endl;
    for (size_t i = 0; i < v.robot_cmd_vel.size(); ++i)
    {
      s << indent << "  robot_cmd_vel[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "    ", v.robot_cmd_vel[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_CMD_VEL_H
